version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: news-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: news_db
    networks:
      - news-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - NEWSAPI_KEY=${NEWSAPI_KEY:-your_newsapi_key}
      - GUARDIAN_KEY=${GUARDIAN_KEY:-your_guardian_key}
    depends_on:
      - mongodb
    volumes:
      - ./backend/app:/app/app
    networks:
      - news-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - news-network

volumes:
  mongodb_data:
    driver: local

networks:
  news-network:
    driver: bridge

